### ISSUE TITLE
Needs different authentication (SignatureV4)

### ISSUE THREAD

**Issue by martinvirtel** [eschultink/S3-for-Google-Apps-Script#1]
Hi, my AWS S3 service gives this error: 

![image](https://cloud.githubusercontent.com/assets/9485782/12826743/ce9b1ef2-cb7c-11e5-8557-54987ef48260.png)

So I googled the instructions from AMZN ;-) 

http://docs.aws.amazon.com/general/latest/gr/signature-version-4.html

**Comment by welshamy** [comment]
@martinvirtel @eschultink problem still persists with the patch.

**Comment by tymccabe** [comment]
@usdivad @martinvirtel @eschultink was a solution to this ever found?

**Comment by TranBaVinhSon** [comment]
@martinvirtel @eschultink  did you solve your problem ?

**Comment by eschultink** [comment]
have merged #6 which seems to solve this; but not well-tested, so ymmv
